/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddblogRouteImport } from './routes/addblog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogIdRouteImport } from './routes/$blogId'
import { Route as IndexRouteImport } from './routes/index'

const AddblogRoute = AddblogRouteImport.update({
  id: '/addblog',
  path: '/addblog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$blogId',
  path: '/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$blogId': typeof BlogIdRoute
  '/about': typeof AboutRoute
  '/addblog': typeof AddblogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$blogId': typeof BlogIdRoute
  '/about': typeof AboutRoute
  '/addblog': typeof AddblogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$blogId': typeof BlogIdRoute
  '/about': typeof AboutRoute
  '/addblog': typeof AddblogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$blogId' | '/about' | '/addblog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$blogId' | '/about' | '/addblog'
  id: '__root__' | '/' | '/$blogId' | '/about' | '/addblog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogIdRoute: typeof BlogIdRoute
  AboutRoute: typeof AboutRoute
  AddblogRoute: typeof AddblogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/addblog': {
      id: '/addblog'
      path: '/addblog'
      fullPath: '/addblog'
      preLoaderRoute: typeof AddblogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$blogId': {
      id: '/$blogId'
      path: '/$blogId'
      fullPath: '/$blogId'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogIdRoute: BlogIdRoute,
  AboutRoute: AboutRoute,
  AddblogRoute: AddblogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
